### ISSUE TITLE
cross-publish for 2.13.0-M1

### ISSUE THREAD

**Issue by MasseGuillaume** [lihaoyi/autowire#62]

**Comment by aginiewicz** [comment]
Any news on 2.13 support now that it is released? Would be cool to see this (and scala.rx) published for 2.13.

**Comment by cilicio** [comment]
Please, support this

**Comment by sjrd** [comment]
The latest master branch seems to have support for Scala 2.13.x, but there are no published artifacts on Maven for 2.13.x.

Since it seems maintainance has resumed in this repo, would it possible to get a 2.13.x version published?

I'm trying to upgrade [Hands-on Scala.js](http://www.lihaoyi.com/hands-on-scala-js/) for Scala.js 1.x and Scala 2.13.x, and Autowire seems to be the last missing dependency.

**Comment by mathieuleclaire** [comment]
The last commits and PR merges do this. We are just doing the release. Have look there: https://github.com/lihaoyi/autowire/pull/88

**Comment by sjrd** [comment]
Oh great, thank you. Looking forward to it :)
